version: '3.3'
services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    #volumes:
      #- ./data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=secret
